Added Modal component
capitec/omni-components pull request #133
Opened 2023-05-22 11:04 UTC by BOTLANNER

### Description:

Control to display modal content with optional header and footer content.

### Screenshots (if appropriate):
![image](https://github.com/capitec/omni-components/assets/16349308/7629a75a-5c03-4553-b9bb-b26998cf378c)

### All Submissions:

* [X] I have followed the [contribution guidelines](https://github.com/capitec/omni-components/blob/develop/CONTRIBUTING.md) for this project.
* [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.

### Changes to Core Features:

* [X] I have added an explanation of what my changes do and why I would like to include them.
* [X] I have written new tests for my core changes, as applicable.
* [X] I have successfully ran tests with my changes locally.
* [X] I have added/updated docs, as applicable.

2023-05-22 11:56 UTC, chromaticWaster commented on src/modal/Modal.ts
> + * @slot - Content to render inside the component body.
Add slot name

2023-05-22 13:49 UTC, chromaticWaster commented on src/modal/Modal.ts
> + * @slot - Content to render inside the component body.
Noted that this is the default slot

2023-05-22 14:00 UTC, chromaticWaster approved these changes

2023-05-22 14:15 UTC, stefan505 requested changes

2023-05-22 14:15 UTC, stefan505 commented on src/modal/Modal.stories.ts
Consider modal close actions using buttons or icons or something.

2023-05-22 14:15 UTC, stefan505 commented on src/modal/Modal.ts
> +        <dialog part="dialog" class="modal" role="dialog" aria-modal="true"
Check indentation for template result functions, looks like tabs & spaces are mixed.

2023-05-23 08:01 UTC, stefan505 approved these changes

2023-05-23 08:01 UTC, merged