Add expander component
capitec/omni-components pull request #182
Opened 2023-08-17 11:09 UTC by chromaticWaster

### Description:

 **Add Expander and Expander Group components**

closes #159 

- Added the Expander and Expander Group components.
- Added visual and behaviour tests.
- Added relevant stories.

(*Link to bug/feature from [Issues](../issues) and how you resolve it*)

### Screenshots (if appropriate):

**Expander**

https://github.com/capitec/omni-components/assets/22874454/6971e9ae-49e5-4016-8d3f-0d3ea5dfc698

**Expander Group** 

https://github.com/capitec/omni-components/assets/22874454/be63f664-3869-4dcf-980d-9c6ee66104e4

**Expander test results** 

<img width="147" alt="image" src="https://github.com/capitec/omni-components/assets/22874454/014aa322-45b2-4e59-b22f-a81b21739ffd">

**Expander Group test results**
 
<img width="147" alt="image" src="https://github.com/capitec/omni-components/assets/22874454/92d8979b-4d0a-404d-a902-a59c2b0380d9">

### All Submissions:

* [x] I have followed the [contribution guidelines](https://github.com/capitec/omni-components/blob/develop/CONTRIBUTING.md) for this project.
* [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.

### Changes to Core Features:

* [x] I have added an explanation of what my changes do and why I would like to include them.
* [x] I have written new tests for my core changes, as applicable.
* [x] I have successfully ran tests with my changes locally.
* [x] I have added/updated docs, as applicable.

2023-08-17 17:22 UTC, stefan505 approved these changes

2023-08-21 07:35 UTC, BOTLANNER requested changes

2023-08-21 07:35 UTC, BOTLANNER commented on src/expander/Expander.ts
> + *
Document events

2023-08-21 07:35 UTC, BOTLANNER commented on src/expander/ExpanderGroup.ts
> +        this._observer = new MutationObserver((mutations) => {
Consider using events instead

2023-08-21 08:26 UTC, chromaticWaster commented on src/expander/Expander.ts
> + *
Documented as requested.

2023-08-21 08:26 UTC, chromaticWaster commented on src/expander/ExpanderGroup.ts
> +        this._observer = new MutationObserver((mutations) => {
Updated to use events as requested.

2023-08-21 10:54 UTC, BOTLANNER approved these changes

2023-08-21 11:34 UTC, merged