Alpha
capitec/omni-components pull request #97
Opened 2023-03-22 08:59 UTC by chromaticWaster

### Description:

Closes - https://github.com/capitec/omni-components/issues/68

- Date picker component
- Calendar component 
- Keyboard component - in experimental phase

### Screenshots (if appropriate):

**Test results**

![image](https://user-images.githubusercontent.com/22874454/226849831-d5458055-6285-4afc-8f3e-1a5c251c6507.png)

**Date Picker**

![Date picker component](https://user-images.githubusercontent.com/22874454/226850762-39169877-32fd-444e-8f86-8537278476ad.gif)

**Calendar** 

![Calendar component](https://user-images.githubusercontent.com/22874454/226851204-963b9184-2b06-433d-89c2-47162d69ea52.gif)

### All Submissions:

* [x] I have followed the guidelines in the Contributing document.
* [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.

### Changes to Core Features:

* [x] I have added an explanation of what my changes do and why I would like to include them.
* [x] I have written new tests for my core changes, as applicable.
* [x] I have successfully ran tests with my changes locally.
* [x] I have added/updated docs, as applicable.

2023-03-22 14:06 UTC, stefan505 requested changes

2023-03-23 08:25 UTC, chromaticWaster commented on src/calendar/Calendar.stories.ts
> +    description: 'Set the value of the Calendar component, this has to be a valid date in ISOformat',
Changes implemented as requested.

2023-03-23 08:25 UTC, chromaticWaster commented on src/date-picker/DatePicker.stories.ts
> +    title: 'UI Components/Select',
Changes implemented as requested.

2023-03-23 08:25 UTC, chromaticWaster commented on src/date-picker/DatePicker.stories.ts
> +    component: 'omni-select'
Changes implemented as requested.

2023-03-23 08:25 UTC, chromaticWaster commented on src/date-picker/DatePicker.stories.ts
> +    description: 'Set the current value of the Date picker component.',
Changes implemented as requested.

2023-03-23 08:25 UTC, chromaticWaster commented on src/date-picker/DatePicker.stories.ts
> +    description: 'Set the current locale of the Date picker component.',
Changes implemented as requested.

2023-03-23 08:25 UTC, chromaticWaster commented on src/date-picker/DatePicker.ts
> + * Control that allows you to select a specific date
Changes implemented as requested.

2023-03-23 08:26 UTC, chromaticWaster commented on src/date-picker/DatePicker.ts
> +    _mobileCheck() {
Function removed as it wont be required.

2023-03-23 12:44 UTC, stefan505 approved these changes

2023-03-23 12:44 UTC, merged